name: flutter_mobile_app
description: A Flutter app for the pawnshop_management backend
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  # ...existing dependencies...

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # ...existing configuration...
