# Generated by Django 5.2.4 on 2025-07-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_rename_schemes_sche_status_e91afc_idx_schemes_sch_status_739aec_idx_and_more'),
        ('schemes', '0002_schemeauditlog'),
    ]

    operations = [
    ]
