# Generated by Django 5.2.4 on 2025-07-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_fix_item_photos'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL to remove the item_id constraint from the transactions_loan table
            """
            ALTER TABLE transactions_loan 
            DROP COLUMN IF EXISTS item_id;
            """,
            # Reverse SQL (not typically needed, but included for completeness)
            """
            ALTER TABLE transactions_loan
            ADD COLUMN item_id integer NULL;
            """
        ),
    ]
