# Generated by Django 5.2.4 on 2025-07-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20250704_1843'),
        ('accounts', '0007_ensure_role_defaults'),  # Make sure we depend on the latest accounts migration
    ]

    operations = [
        migrations.RunSQL(
            # SQL to update the foreign key constraint
            """
            -- First, check if the constraint exists before trying to drop it
            DO $$
            BEGIN
              IF EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'transactions_loan_customer_id_785c86c2_fk_transacti'
              ) THEN
                -- Drop the existing constraint
                ALTER TABLE transactions_loan 
                DROP CONSTRAINT IF EXISTS transactions_loan_customer_id_785c86c2_fk_transacti;
              END IF;
              
              -- Add the correct constraint referencing accounts_customer
              ALTER TABLE transactions_loan
              ADD CONSTRAINT transactions_loan_customer_id_fk_accounts_customer
              FOREIGN KEY (customer_id) 
              REFERENCES accounts_customer(id)
              ON DELETE CASCADE;
            END;
            $$;
            """,
            # Reverse SQL (to revert if needed)
            """
            ALTER TABLE transactions_loan 
            DROP CONSTRAINT IF EXISTS transactions_loan_customer_id_fk_accounts_customer;
            """
        ),
    ]
