# Generated by Django 5.2.1 on 2025-06-16 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for reference', max_length=50, unique=True)),
                ('scheme_type', models.CharField(choices=[('standard', 'Standard'), ('flexible', 'Flexible'), ('premium', 'Premium'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate as a percentage (e.g. 12.00 for 12%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duration_days', models.IntegerField(help_text='Standard duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('no_interest_period_days', models.IntegerField(default=0, help_text='Number of days without interest if repaid early', validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_period_days', models.IntegerField(default=0, help_text='Minimum period before loan can be closed (0 for no minimum)', validators=[django.core.validators.MinValueValidator(0)])),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Processing fee as a percentage of loan amount', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for global schemes available to all branches', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Loan Scheme',
                'verbose_name_plural': 'Loan Schemes',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'branch'), name='unique_scheme_per_branch')],
            },
        ),
    ]
