# Generated by Django 5.2.1 on 2025-06-16 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_region'),
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_loans_count', models.PositiveIntegerField(default=0)),
                ('active_loans_count', models.PositiveIntegerField(default=0)),
                ('completed_loans_count', models.PositiveIntegerField(default=0)),
                ('defaulted_loans_count', models.PositiveIntegerField(default=0)),
                ('total_principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_processing_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='content_manager.scheme')),
            ],
            options={
                'verbose_name': 'Scheme Usage Statistic',
                'verbose_name_plural': 'Scheme Usage Statistics',
                'ordering': ['-end_date', 'scheme'],
                'unique_together': {('scheme', 'branch', 'start_date', 'end_date')},
            },
        ),
    ]
