# Generated by Django 5.2.1 on 2025-06-16 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_region'),
        ('content_manager', '0002_schemeusagestats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_scheme', 'New Scheme Launched'), ('expiring_soon', 'Scheme Expiring Soon'), ('high_performance', 'High Performance Scheme'), ('special_offer', 'Special Offer'), ('promotion', 'Promotional Scheme')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('start_date', models.DateField(help_text='When this notification becomes active')),
                ('end_date', models.DateField(help_text='When this notification expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave empty to notify all branches', null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheme_notifications', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='content_manager.scheme')),
            ],
            options={
                'ordering': ['-start_date', '-priority'],
            },
        ),
    ]
